fragment ModifierParts on Modifier {
  name
  price
}

fragment MenuParts on Menu {
  name
  section {
    __typename
    name
    item {
      __typename
      name
      description
      price
      dietary
      available
    }
  }
}

fragment PostsParts on Posts {
  title
  body
}
