fragment MenusParts on Menus {
  menu {
    __typename
    name
    label
    description
    section {
      __typename
      name
      item {
        __typename
        name
        description
        price
        dietary
        modifier {
          __typename
          name
          price
        }
        available
      }
    }
  }
}

fragment PostsParts on Posts {
  title
  body
}
