fragment MenusParts on Menus {
  menu {
    __typename
    name
    label
    description
    sections {
      __typename
      name
      items {
        __typename
        name
        description
        price
        dietary
        modifiers {
          __typename
          name
          price
        }
        available
        images {
          __typename
          name
          src
        }
      }
    }
  }
}

fragment PostsParts on Posts {
  title
  body
}
